sudo: false
language: php
php:
  - 7.1
  - 7.2
  - 7.4
before_script:
  - sudo apt-get -y install python-pytest
  - mv src/function src/a
script: 
  - sh travis-ci.sh src
  - py.test -q generate_file_lists.py
after_script:
  - cat myerrorfile
